### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by saba586** [DaneeSkripter/PollButtons#1]
Can you add permission? I dont want members to use commands.

**Comment by daneedev** [comment]
@Grimb1e Hello, if you want permissions just do it manually in discord:

**1) Go to server settings**
**2) Then click [Integrations](https://clickimg.xyz/i/JRCgfP6.png)** 
**3) Choose PollButtons**
**4) There will be all [commands](https://clickimg.xyz/i/kWDQqAl.png)**
**5) Choose [command](https://clickimg.xyz/i/qqvNDrc.png) and you can change permissions**

Have a nice day,
DaneeSkripter - Founder of PollButtons

**Comment by saba586** [comment]
okay, thanks.
